# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file '/Users/attfsh/x/better.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(766, 539)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 761, 521))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.firstRoute = QtWidgets.QWidget()
        self.firstRoute.setObjectName("firstRoute")
        self.k2Edit = QtWidgets.QLineEdit(self.firstRoute)
        self.k2Edit.setGeometry(QtCore.QRect(60, 40, 113, 21))
        self.k2Edit.setObjectName("k2Edit")
        self.label_2 = QtWidgets.QLabel(self.firstRoute)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 21, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.firstRoute)
        self.label_4.setGeometry(QtCore.QRect(350, 80, 59, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.firstRoute)
        self.label.setGeometry(QtCore.QRect(10, 10, 21, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.deciphButton = QtWidgets.QPushButton(self.firstRoute)
        self.deciphButton.setGeometry(QtCore.QRect(380, 20, 114, 32))
        self.deciphButton.setObjectName("deciphButton")
        self.label_3 = QtWidgets.QLabel(self.firstRoute)
        self.label_3.setGeometry(QtCore.QRect(350, 240, 59, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.firstRoute)
        self.label_5.setGeometry(QtCore.QRect(350, 400, 59, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.outputEdit = QtWidgets.QTextEdit(self.firstRoute)
        self.outputEdit.setGeometry(QtCore.QRect(430, 80, 311, 341))
        self.outputEdit.setReadOnly(True)
        self.outputEdit.setObjectName("outputEdit")
        self.ciphButton = QtWidgets.QPushButton(self.firstRoute)
        self.ciphButton.setGeometry(QtCore.QRect(260, 20, 111, 31))
        self.ciphButton.setCheckable(False)
        self.ciphButton.setObjectName("ciphButton")
        self.inputEdit = QtWidgets.QTextEdit(self.firstRoute)
        self.inputEdit.setGeometry(QtCore.QRect(20, 80, 311, 341))
        self.inputEdit.setObjectName("inputEdit")
        self.k1Edit = QtWidgets.QLineEdit(self.firstRoute)
        self.k1Edit.setGeometry(QtCore.QRect(60, 10, 113, 21))
        self.k1Edit.setObjectName("k1Edit")
        self.tabWidget.addTab(self.firstRoute, "")
        self.second = QtWidgets.QWidget()
        self.second.setObjectName("second")
        self.cipherText = QtWidgets.QPlainTextEdit(self.second)
        self.cipherText.setGeometry(QtCore.QRect(40, 20, 311, 181))
        self.cipherText.setObjectName("cipherText")
        self.label_6 = QtWidgets.QLabel(self.second)
        self.label_6.setGeometry(QtCore.QRect(40, 210, 201, 16))
        self.label_6.setObjectName("label_6")
        self.statsTable = QtWidgets.QTableWidget(self.second)
        self.statsTable.setGeometry(QtCore.QRect(40, 240, 201, 192))
        self.statsTable.setShowGrid(False)
        self.statsTable.setColumnCount(2)
        self.statsTable.setObjectName("statsTable")
        self.statsTable.setRowCount(0)
        self.cipherLF = QtWidgets.QLineEdit(self.second)
        self.cipherLF.setGeometry(QtCore.QRect(420, 240, 31, 21))
        self.cipherLF.setObjectName("cipherLF")
        self.openLF = QtWidgets.QLineEdit(self.second)
        self.openLF.setGeometry(QtCore.QRect(590, 240, 31, 21))
        self.openLF.setObjectName("openLF")
        self.cipherLS = QtWidgets.QLineEdit(self.second)
        self.cipherLS.setGeometry(QtCore.QRect(420, 280, 31, 21))
        self.cipherLS.setObjectName("cipherLS")
        self.openLS = QtWidgets.QLineEdit(self.second)
        self.openLS.setGeometry(QtCore.QRect(590, 280, 31, 21))
        self.openLS.setObjectName("openLS")
        self.label_7 = QtWidgets.QLabel(self.second)
        self.label_7.setGeometry(QtCore.QRect(370, 210, 141, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.second)
        self.label_8.setGeometry(QtCore.QRect(530, 210, 171, 16))
        self.label_8.setObjectName("label_8")
        self.attack = QtWidgets.QPushButton(self.second)
        self.attack.setGeometry(QtCore.QRect(470, 320, 114, 32))
        self.attack.setObjectName("attack")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.second)
        self.plainTextEdit.setGeometry(QtCore.QRect(400, 20, 321, 181))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_9 = QtWidgets.QLabel(self.second)
        self.label_9.setGeometry(QtCore.QRect(410, 360, 59, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.second)
        self.label_10.setGeometry(QtCore.QRect(410, 400, 59, 16))
        self.label_10.setObjectName("label_10")
        self.findk1 = QtWidgets.QLabel(self.second)
        self.findk1.setGeometry(QtCore.QRect(570, 360, 59, 16))
        self.findk1.setText("")
        self.findk1.setObjectName("findk1")
        self.findk2 = QtWidgets.QLabel(self.second)
        self.findk2.setGeometry(QtCore.QRect(570, 400, 59, 16))
        self.findk2.setText("")
        self.findk2.setObjectName("findk2")
        self.transportButt = QtWidgets.QPushButton(self.second)
        self.transportButt.setGeometry(QtCore.QRect(403, 430, 241, 32))
        self.transportButt.setObjectName("transportButt")
        self.tabWidget.addTab(self.second, "")
        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

def retranslateUi(self, Form):
    _translate = QtCore.QCoreApplication.translate
    Form.setWindowTitle(_translate("Form", "Form"))
    self.label_2.setText(_translate("Form", "k2"))
    self.label_4.setText(_translate("Form", "->"))
    self.label.setText(_translate("Form", "k1"))
    self.deciphButton.setText(_translate("Form", "Дешифров"))
    self.label_3.setText(_translate("Form", "->"))
    self.label_5.setText(_translate("Form", "->"))
    self.outputEdit.setPlaceholderText(_translate("Form","Полученный результат будет здесь"))
    self.ciphButton.setText(_translate("Form", "Шифрование"))
    self.inputEdit.setPlaceholderText(_translate("Form", "Введите текст здесь"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.firstRoute), _translate("Form", "Шифрование/дешифрование"))
    self.cipherText.setPlaceholderText(_translate("Form", "Шифротекст"))
    self.label_6.setText(_translate("Form", "Статистика шифротекста"))
    self.statsTable.setSortingEnabled(True)
    self.label_7.setText(_translate("Form", "Символ шифротекста"))
    self.label_8.setText(_translate("Form", "Символ открытого текста"))
    self.attack.setText(_translate("Form", "Атаковать"))
    self.plainTextEdit.setPlaceholderText(_translate("Form", "Открытый текст"))
    self.label_9.setText(_translate("Form", "k1"))
    self.label_10.setText(_translate("Form", "k2"))
    self.transportButt.setText(_translate("Form", "Дешифровать ключами"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.second), _translate("Form", "Криптоанализ"))
    self.statsTable.setHorizontalHeaderLabels(['Символ', 'Частота'])
